### ISSUE TITLE
Problems in recognizing Bash 4.3

### ISSUE THREAD

**Issue by holgerman** [koriege/muvac#1]
Hi,
thank you for the work! I have the problem that my bash 4.3 is not recognized. The problem seems to come that my OS (openSUSE 42.2 (x86_64), VERSION = 42.2, CODENAME = Malachite) writes the string **version** capitalized (**V**ersion instead of **v**ersion):

bash -version | head -1
GNU bash, Version 4.3.42(1)-release (x86_64-suse-linux-gnu)

I experienced it in vs. 0.1.2 (installed by the root, not me) but the recent change in 0.1.3 still seems to have the same problem:
bash -version | head -1 | perl -lane 'if ($_=~/version\s+4\.(\d+)/){if($1>=3){print 1}else{print 0}}else{print 0}'
0

Thanks!
Holger

**Comment by koriege** [comment]
Hi,
I updated the version check to be case insensitive. Thanks for pointing this out!
Cheers

**Comment by holgerman** [comment]
Thanks, this worked fine now!
