### ISSUE TITLE
Problems creating java memory parameter

### ISSUE THREAD

**Issue by holgerman** [koriege/muvac#2]
Hi,
I run into another problem: 
After the fastq, the trimming section starts with an error: 
> :INFO: trimming
> Invalid maximum heap size: -Xmx-18g
> 
Indeed, in muvac, the creation of the memory parameter in row 1225  is
> memory=$(script -e -q -c "stty rows 1000; top -b -n 1" /dev/null | grep 'KiB Mem' | perl -lane '$_=~/(\d+)\D+(\d+)\D+(\d+)/; printf("%d",($1-$3)/1024/1024)')

so that on my OS (openSUSE 42.2 (x86_64), VERSION = 42.2, CODENAME = Malachite) 
the parameter memory becomes _-18_ and later on _-Xmx-18g_ instead of _18_  and later on _-Xmx18g_ causing an error.

Thanks again!
Holger

**Comment by koriege** [comment]
Hi,
unfortunately I cannot reproduce this on my openSuse VM. However, muvac now uses an other method to determine free memory. 
Just clone the repo again..
Cheers

**Comment by holgerman** [comment]
Thanks, the problem is gone, great.
