### ISSUE TITLE
Segemehl fails

### ISSUE THREAD

**Issue by holgerman** [koriege/muvac#3]
Unfortunately, I run into another problem, where segemehl failed. here is the log file:
[170614test2.log.txt](https://github.com/koriege/muvac/files/1077760/170614test2.log.txt)

If you like you can send me two fastq files that previously run in your hands in order to exclude any problems due to the input data.

Thanks again!
Best, Holger

**Comment by koriege** [comment]
from [http://seqanswers.com/forums/showthread.php?t=61522](seqanswers)
"If this error occurs, segemehl cannot assign mate2 to mate1. Are the reads in both your files in correct order? Do they have matching read ids (at least the beginning of the id)? Do you have the same number of reads in the mate1 file and the mate2 file? 

Segemehl tries to find the two mates that belong together by checking the fastq identifiers. 
They have to be:
completely identical,
contain identical substring (everything before the first whitespace), or
identical with a '/1', or a '/2' at their ends"

Please make sure your raw input files  ..lib59758_3231_7_1.fastq and ..lib59750_3164_5_1.fastq belong together

**Comment by koriege** [comment]
I added two fastq files to the repository for testing purposes
Cheers
